### ISSUE TITLE
[VolumeController] Code ANE VolumeController - phần Native library - Android

### ISSUE THREAD

**Issue by nganntk** [NganNTK/SE-AIRNativeExtension#5]
- Code phần thư viện android
- Hiểu được FREExtension, FREContext, FREFunction sử dụng như thế nào

**Comment by NhuNga96** [comment]
Với tính chất đặc thù của ANE thì issue này sẽ được gộp chung.
https://github.com/se-ane/SE-AIRNativeExtension/issues/4
Do đó, issue này sẽ được đóng lại
