### ISSUE TITLE
[VolumeController] Code ANE VolumeController - phần Native library - iOS

### ISSUE THREAD

**Issue by nganntk** [NganNTK/SE-AIRNativeExtension#8]
Code phần thư viện iOS

**Comment by thanhphamvan** [comment]
Đã ghi nhận, sẽ hoàn thành các yêu cầu trước Deadline!

**Comment by Huongltt199** [comment]
Mn ơi, nên test theo hình thức nào nhỉ @HuongVT311 @NhuNga96 , và nhóm có định thêm chức năng phụ gì không?

**Comment by nganntk** [comment]
@Huongltt199 Phần test thảo luận bên issue test đi cậu ơi

**Comment by thanhphamvan** [comment]
https://github.com/se-ane/SE-ANE-iOS-VolumeController/commit/dc4f5171d3633c4db6bda308527134828ac61faf
Release first stable build, need more testing.

**Comment by NhuNga96** [comment]
Với tính chất đặc thù của ANE thì issue này sẽ được gộp chung.
https://github.com/se-ane/SE-AIRNativeExtension/issues/4
Do đó, issue này sẽ được đóng lại

**Comment by NhuNga96** [comment]
Hiện tại phần ios chưa build được package để test trên thiết bị
=> mô tả trong issue https://github.com/se-ane/SE-AIRNativeExtension/issues/32
